# Generated by Django 3.2.9 on 2022-12-29 11:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_userlikedpost"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid1, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="userlikedpost",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid1, editable=False, unique=True),
        ),
    ]
